spring:
    liquibase:
        enabled: true
    datasource:
        url: jdbc:h2:file:./db
        driverClassName: org.h2.Driver
        username: mikhail
        password: 1
    h2:
        console:
            enabled: true


